window.languageDic={
  "en":{
  "appTitle":"Web Quick Editing",
  "tm":"Task Monitor",
  "hello":"Webcome,",
  "content":"Content",
  "effect":"Effect",
  "pageTitle":"Web Quick Editing",
	"baseClass" :"Base class must override the name method, return the plugin name.",
	"plugin":"Plugin: ",
	"repeat":" repeat",
	"trackBelongOthers":"There are other media on the track, please remove it first.",
	"trackNotExist":"The track does not exist.",
	"empty":"Empty",
	"buffering":"Buffering...",
	"errorOfNetwork":"Error: network error",
	"errorOfMedia":"Error: media format error, unable to decode",
	"errorOfResource":"Error: unable to access media resources",
	"error":"error",
	"projectInfo":"Project information",
	"name":"Name",
	"unnamed":"Unnamed",
	"frameRate":"Frame rate",
	"breadth":"Breadth",
	"video":"Video",
	"audio":"Audio",
	"subtitle":"Subtitle",
	"picture":"Image",
	"trackBelongOtherLayer":"The track item has already belonged to a layer, please remove the binding first.",
	"adjustInOutPoint":"Adjust in/out point",
	"addItemL":"Add item[",
	"addItemR":"]",
	"insertItem":"Insert item",
	"adjustItemLoc":"Adjust item location",
	"moveItem":"Move item",
	"deleteItem":"Delete item",
	"wrongStart":"Wrong Start Time",
	"wrongEnd":"Wrong End Time",
	"startTimeGreater":"Start time is greater than the end time",
	"subclassMustType":"Subclasses must override the PopcornPlugin type",
	"subclassMustName":"Subclasses must override the name",
	"operation":"Operation",
	"colorUpdateError":"Color update error",
	"colorValueError":"Color value error",
	"theEditorL":"The Editor \"",
	"theEditorR":"\" does not exist.",
	"editorLayoutWrong":"The layout of editor is wrong",
	"MSYH":"Microsoft YaHei",
	"song":"SimSun",
	"startTimeError":"Start time error, has adjusted automatically",
	"endTimeError":"End time error, has adjusted automatically",
	"default":"Set as default",
	"second":"Second",
	"noMetadata":"With no metadata",
	"fade":"Fade-in/Fade-out",
	"flashBlack":"Flash Black",
	"flashWhite":"Flash White",
	"markPointM":"Add Marker(M)",
	"tip":"Tip",
	"markPointEmpty":"The Mark point remark can't be empty",
	"markPoint":"Mark List",
	"property":"Property",
	"displayPropertyInfo":"Display the Property Information of active object",
	"modifyE":"Modify program information(E)",
	"newN":"New(Ctrl+E)",
	"timelineEmpty":"The timeline is not empty, do you want to save it first?",
	"clearTimeline":"Are you sure to clear out the timeline?",
	"saveS":"Save(S)",
	"revokeZ":"Undo(Ctrl+Z)",
	"redoR":"Redo(Ctrl+Y)",
	"addSubtitleT":"Add Subtitle(T)",
	"subtitleExisted":"The current area has already existed the subtitle, please add the caption in the blank area.",
	"tobegin":"To the beginning(Home)",
	"lastFrame":"Last frame(←)",
	"playOrPause":"Play/Pause(Space)",
	"nextFrame":"Next frame(→)",
	"toEnd":"To the end(End)",
	"inL":"In([)",
	"outR":"Out(])",
	"cut":"Split(P)",
	"delete":"Delete(Delete)",
	"yes":"Yes",
	"no":"No",
	"confirm":"Confirm",
	"cancel":"Cancel",
	"inOrOutPoint":"In/Out point",
	"in":"In",
	"out":"Out",
	"markInGreater":"Mark In time is greater than Mark Out time.",
	"markoutLess":"Mark Out time is less than Mark In time.",
	"remarkEmpty":"The Mark point remark can't be empty.",
	"selectMarkPoint":"Please select the mark point!",
	"welcomeToUse":"Welcome to use the artDialog dialog components!",
	"welcome":"Welcome",
	"description":"Comments",
	"buffer":"Buffering",
	"dragToChange":"Drag to change the current time.",
	"clickOrDblclick":"Click the lock / unlock, double click to lock the other tracks(Except the current track)",
	"createTime":"Create time",
	"markPointRemark":"Mark point remark:",
	"edit":"Video",
	"programInfo":"Program Information",
	"textEditor":"Text editor",
	"basic":"Basic",
	"advanced":"Advanced",
	"warning":"Warning:",
	"pressEnter":"Press Enter to Confirm",
	"mediaElement":"Media Element",
	"start":"Start",
	"end":"End",
	"active":"Active",
	"showOrHide":"Show / hide",
	"wrongTimeFormat":"Wrong time format",
	"create":"Create",
	"timelineEmptyNotSave":"The timeline is empty, can't be saved!",
	"success":"Success",
	"saveSuccess":"Save success!",
	"saveFailed":"Save failed!\n",
	"errorUp":"Error",
	"notSetSaveMethod":"Didn't set the save method, can't save the timeline.",
	"initializeFirst":"Please initialize first",
	"signatureTimeout":"Signature timeout, please regenerate a new signature.",
	"generateSignature":"Generate signature:",
	"preload":"Pre-load the next material...",
	"notSupportL":"Can't support the ",
	"notSupportR":" TrackEvent",
	"text":"Text",
	"customize":"Customize",
	"center":"Center",
	"bottom":"Bottom",
	"top":"Top",
	"textPosition":"Text position",
	"left":"Left",
	"right":"Right",
	"alignment":"Alignment",
	"finish":"Finish",
	"font":"Font",
	"fontSize":"Font Size",
	"fontColor":"Font Color",
	"shadow":"Shadow",
	"shadowColor":"Shadow Color",
	"background":"Background",
	"backgroundColor":"Background Color",
	"boldface":"Boldface",
	"italic":"Italic",
	"leftMargin":"Left Margin",
	"topMargin":"Top Margin",
	"width":"Width",
	"address":"Address",
	"height":"Height",
	"color":"Color",
	"sum":"Sum",
	"subtract":"Subtract",
	"multiply":"Multiply",
	"normal":"Normal",
	"renderMethod":"Render method",
	"transition":"Transition",
	"sendToRender":"Send to render",
	"ok":"OK",
	"startAt":"Start at",
	"target":"Target",
	"addSubtitle":"Double click to add subtitle.",
	"search":"search",
	"directory":"Directory",
	"title":"Title",
	"saveAsEdl":"Save As New EDL",
	"saveAsClip":"Save As Clip",
	"clearOut":"Clear out(\\)",
	"confirmFlag":"Confirm",
	"share":"Share",
	"export":"Export to 3rd Party",
	"register":"Register to OA",
	"renderSuccess":"Save as clip success!",
	"saveTileLineSuccess":"Save timeline success!",
	"saveTileLineFailed":"Save timeline Failed!",
	"notGetStream":"Can not get clip stream info!",
	"notGetFormat":"Can not find format info!",
	"getClipInfoFailed":"Get clip info failed!",
	"loadTimelineFailed":"Load Timeline failed",
	"emptyFolderList":"Empty folder list!",
	"getFolderListFailed":"Get folder list failed!",
	"openFolderFailed":"Open folder failed!",
	"getClipListFailed":"Get clip list failed!",
	"emptyResult":"Empty result!",
    "logout":"Close",
    "help":"Help",
    "sort":"Sort",
    "advancesearch":"Advance Search",
    "time":"Create Time",
    "type":"Type",
    "mv":"MV",
    "sv":"SV",
    "welcome":"Welcome ",
    "saveEdl":"Update the EDL",
    "timeLineEmpty":"Timeline is empty!",
    "renderFailed":"Save as clip failed!",
    "updateSuccessfully":"EDL update successfully!",
    "updatefailed":"EDL update failed!",
    "selectPath":"Save path can not be empty!",
    "noLengthInfo":"Can't get the length info!",
    "taskmonitor" :"Task Monitor",
    "timeLineIsEmpty":"The timeline is empty, can't be saved!",
    "canNotAdd":"Can not add to timeline!",
    "errorWord":" Can't contain the illegal characters!",
    "isShowVideoStandard":false,
    "isShowSizes":false
  },
  "cn":{
    "content":"内容",
    "effect":"特效",
    "pageTitle":"在线快编",
	"baseClass" :"基类必须重写name方法，返回插件名称。",
	"plugin":"插件: ",
	"repeat":" 重复",
	"trackBelongOthers":"轨已属于其他媒体，请先移除。",
	"trackNotExist":"轨不存在。",
	"empty":"Empty",
	"buffering":"正在缓冲...",
	"errorOfNetwork":"错误: 网络错误",
	"errorOfMedia":"错误: media format error, unable to decode",
	"errorOfResource":"错误: unable to access media resources",
	"error":"错误",
	"projectInfo":"项目信息",
	"name":"名称",
	"unnamed":"未命名",
	"frameRate":"帧率",
	"breadth":"Breadth",
	"video":"视频",
	"audio":"音频",
	"subtitle":"字幕",
	"picture":"图片",
	"trackBelongOtherLayer":"The track item has already belonged to a layer, please remove the binding first.",
	"adjustInOutPoint":"入出点",
	"addItemL":"添加项[",
	"addItemR":"]",
	"insertItem":"插入项",
	"adjustItemLoc":"Adjust item location",
	"moveItem":"移动项",
	"deleteItem":"删除项",
	"wrongStart":"错误开始时间",
	"wrongEnd":"错误结束时间",
	"startTimeGreater":"Start time is greater than the end time",
	"subclassMustType":"Subclasses must override the PopcornPlugin type",
	"subclassMustName":"Subclasses must override the name",
	"operation":"操作",
	"colorUpdateError":"Color update error",
	"colorValueError":"Color value error",
	"theEditorL":"The Editor \"",
	"theEditorR":"\" does not exist.",
	"editorLayoutWrong":"The layout of editor is wrong",
	"MSYH":"微软雅黑",
	"song":"SimSun",
	"startTimeError":"Start time error, has adjusted automatically",
	"endTimeError":"End time error, has adjusted automatically",
	"default":"默认",
	"second":"秒",
	"noMetadata":"With no metadata",
	"fade":"淡入淡出",
	"flashBlack":"闪黑",
	"flashWhite":"闪白",
	"markPointM":"标记点(M)",
	"tip":"提示",
	"markPointEmpty":"The Mark point remark can't be empty",
	"markPoint":"标记点",
	"property":"属性",
	"displayPropertyInfo":"Display the Property Information of active object",
	"modifyE":"修改项目信息(E)",
	"newN":"新建(N)",
	"timelineEmpty":"时间线不为空，是否先保存？",
	"clearTimeline":"是否清空时间线？",
	"saveS":"保存(S)",
	"revokeZ":"回退(Z)",
	"redoR":"重做(R)",
	"addSubtitleT":"添加字幕(T)",
	"subtitleExisted":"当前位置已存在字幕，请在空白位置添加字幕。",
	"tobegin":"到起始位置(Home)",
	"lastFrame":"上一帧(←)",
	"playOrPause":"播放/暂停(Space)",
	"nextFrame":"下一帧(→)",
	"toEnd":"到末尾位置(End)",
	"inL":"入([)",
	"outR":"出(])",
	"cut":"剪裁(P)",
	"delete":"删除(Delete)",
	"yes":"Yes",
	"no":"No",
	"confirm":"确认",
	"cancel":"退出",
	"inOrOutPoint":"入/出点",
	"in":"入",
	"out":"出",
	"markInGreater":"Mark In time is greater than Mark Out time.",
	"markoutLess":"Mark Out time is less than Mark In time.",
	"remarkEmpty":"The Mark point remark can't be empty.",
	"selectMarkPoint":"请选择标记点！",
	"welcomeToUse":"Welcome to use the artDialog dialog components!",
	"welcome":"Welcome",
	"description":"描述",
	"buffer":"缓冲",
	"dragToChange":"Drag to change the current time.",
	"clickOrDblclick":"Click the lock / unlock, double click to lock the other tracks(Except the current track)",
	"createTime":"创建时间",
	"markPointRemark":"标记备注:",
	"edit":"编辑",
	"programInfo":"项目信息",
	"textEditor":"文本编辑器",
	"basic":"基本",
	"advanced":"高级",
	"warning":"警告:",
	"pressEnter":"Press Enter to Confirm",
	"mediaElement":"Media Element",
	"start":"开始",
	"end":"结束",
	"active":"活动",
	"showOrHide":"显示 / 隐藏",
	"wrongTimeFormat":"Wrong time format",
	"create":"创建",
	"timelineEmptyNotSave":"时间线为空，保存失败！",
	"success":"成功",
	"saveSuccess":"保存成功！",
	"saveFailed":"保存失败!\n",
	"errorUp":"错误",
	"notSetSaveMethod":"Didn't set the save method, can't save the timeline.",
	"initializeFirst":"Please initialize first",
	"signatureTimeout":"Signature timeout, please regenerate a new signature.",
	"generateSignature":"Generate signature:",
	"preload":"Pre-load the next material...",
	"notSupportL":"Can't support the ",
	"notSupportR":" TrackEvent",
	"text":"文本",
	"customize":"自定义",
	"center":"居中",
	"bottom":"底部",
	"top":"顶部",
	"textPosition":"文本位置",
	"left":"靠左",
	"right":"靠右",
	"alignment":"对齐方式",
	"finish":"完成",
	"font":"字体",
	"fontSize":"字体大小",
	"fontColor":"字体颜色",
	"shadow":"阴影",
	"shadowColor":"阴影颜色",
	"background":"背景",
	"backgroundColor":"背景颜色",
	"boldface":"粗体",
	"italic":"斜体",
	"leftMargin":"左边距",
	"topMargin":"上边距",
	"width":"宽度",
	"address":"地址",
	"height":"高度",
	"color":"颜色",
	"sum":"加",
	"subtract":"Subtract",
	"multiply":"Multiply",
	"normal":"Normal",
	"renderMethod":"Render method",
	"transition":"转场",
	"sendToRender":"Send to render",
	"ok":"OK",
	"startAt":"开始于",
	"target":"Target",
	"addSubtitle":"双击添加字幕。",
	"search":"搜索",
	"directory":"目录",
	"title":"标题",
	"saveAsEdl":"另存时间线",
	"saveAsClip":"发起合成",
	"clearOut":"清空(\\)",
	"confirmFlag":"OkCancel",
	"share":"分享",
	"export":"导出到第三方系统",
	"register":"Register to OA",
	"renderSuccess":"发起合成成功!",
	"saveTileLineSuccess":"保存时间线成功!",
	"saveTileLineFailed":"保存时间线失败!",
	"notGetStream":"未获取到视音频流信息!",
	"notGetFormat":"未获取到视音频格式信息!",
	"getClipInfoFailed":"获取素材信息失败!",
	"loadTimelineFailed":"加载时间线失败",
	"emptyFolderList":"未获取到目录树!",
	"getFolderListFailed":"获取目录树失败!",
	"openFolderFailed":"打开文件夹失败!",
	"getClipListFailed":"获取素材列表失败!",
	"emptyResult":"未搜索到结果!",
    "logout":"关闭",
    "help":"帮助",
    "sort":"排序",
    "advancesearch":"高级搜索",
    "time":"创建时间",
    "type":"类型",
    "mv":"MV",
    "sv":"SV",
    "welcome":"欢迎你  ",
    "saveEdl":"保存时间线",
    "timeLineEmpty":"Timeline is empty!",
    "renderFailed":"发起合成失败!",
    "updateSuccessfully":"EDL update successfully!",
    "updatefailed":"EDL update failed!",
    "selectPath":"Save path can not be empty!",
    "noLengthInfo":"Can't get the length info!",
    "taskmonitor" :"My Task",
    "timeLineIsEmpty":"Empty Timeline!",
    "canNotAdd":"Can not add to timeline!",
    "errorWord":" Can't contain the illegal characters!",
    "isShowVideoStandard":false,
    "isShowSizes":false
  }
}
